version: "3.7"

networks:
    cunhaacNET:
        name: cunhaacNET
        driver: bridge
    reverse-proxy:
        external: true

volumes:
    postgres-data:

services:
    # database:
    #     image: postgres:12
    #     container_name: dev-database
    #     hostname: dev-database
    #     #restart: always
    #     networks:
    #         - cunhaacNET
    #     ports:
    #         - "5432:5432"
    #     env_file:
    #         - configs/postgres.env
    #     volumes:
    #         - "postgres-data:/var/lib/postgresql/data"

    frontend:
        build: frontend/
        image: cunhaacnet-frontend:latest
        container_name: cunhaacNET-frontend
        hostname: cunhaacNET-frontend
        networks:
            - cunhaacNET
            - reverse-proxy
        # env_file:
        #     - configs/postgres.env
        environment:
            - FLASK_APP=main.py
            - MODULE_NAME=cunhaacNET.main
        # depends_on:
        #     - database
