version: "3.7"

networks:
  cunhaacNET:
    name: cunhaacNET
    driver: bridge
  reverse-proxy:
    external: true

volumes:
  mysql-data:

services:
  database:
    image: mysql:5.7
    container_name: cunhaacnet-db
    hostname: cunhaacnet-db
    restart: always
    networks:
      - cunhaacNET
    expose:
      - 3306
    env_file:
      - configs/database.env
    volumes:
      - "mysql-data:/var/lib/mysql"

  frontend:
    build: src/
    image: cunhaacnet-frontend:latest
    container_name: cunhaacnet-frontend
    hostname: cunhaacnet-frontend
    networks:
      - cunhaacNET
      - reverse-proxy
    env_file:
      - configs/flask.env
      - configs/database.env
      - configs/mail.env
    depends_on:
      - database
